apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
  namespace: monitoring
labels:
  role: alert-rules
data:
  alert.rules: |
    groups:
    - name: pod-restart-alerts
      rules:
      - alert: PodRestartTooMany
        expr: pod_restart_count > 5
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Pod {{ $labels.pod }} restart lebih dari 5 kali!"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} sudah restart {{ $value }} kali."

