apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-minimal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ryanraditya/gitops-infra-alternatif.git
    targetRevision: main
    path: monitoring-minimal
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
