apiVersion: v1
kind: Service
metadata:
  name: kubelet-proxy
  namespace: monitoring
spec:
  ports:
  - name: https-metrics
    port: 10250
    targetPort: 10250
  - name: cadvisor
    port: 4194
    targetPort: 4194

