apiVersion: v1
kind: Endpoints
metadata:
  name: kubelet-proxy
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.49.2
    ports:
      - name: https-metrics
        port: 10250
      - name: cadvisor
        port: 4194
