apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-restart-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-restart-exporter
  template:
    metadata:
      labels:
        app: pod-restart-exporter
    spec:
      serviceAccountName: pod-restart-sa
      containers:
      - name: exporter
        image: python:3.10-slim
        ports:
        - containerPort: 9113
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install flask kubernetes > /dev/null 2>&1
            cat << 'EOF' > /exporter.py
            from flask import Flask, Response
            from kubernetes import client, config

            app = Flask(__name__)
            try:
                config.load_incluster_config()
            except:
                config.load_kube_config()
            v1 = client.CoreV1Api()

            @app.route('/metrics')
            def metrics():
                try:
                    pods = v1.list_pod_for_all_namespaces()
                except Exception as e:
                    return Response(str(e), status=500)

                lines = []
                for pod in pods.items:
                    for c in (pod.status.container_statuses or []):
                        restart = c.restart_count
                        lines.append(f'pod_restart_count{{namespace="{pod.metadata.namespace}",pod="{pod.metadata.name}",container="{c.name}"}} {restart}')
                return Response("\n".join(lines), mimetype='text/plain')

            EOF
            python /exporter.py

